### ISSUE TITLE
"not"-operator doesn't seem to be working properly

### ISSUE THREAD

**Issue by Selina-Mutz** [maxlath/wikibase-dump-filter#25]
I tried to get all humans without a death date and used this claim: `--claim 'P31:Q5|~P570'`

It seems to be writing all entries from the overall wikidata dump in the file and not just the requested ones. 
I also tried the claim from the How-To examples but I got the same result. Is there something wrong with the claim I'm using?

**Comment by maxlath** [comment]
sorry, there was an error in the documentation (fixed in db0f0f0): the filter corresponding to humans without a death date should be `--claim 'P31:Q5&~P570'`

**Comment by Selina-Mutz** [comment]
Thank you! It's working now :)
