### ISSUE TITLE
filter all entities that are instances of a subclass of an item 

### ISSUE THREAD

**Issue by Selina-Mutz** [maxlath/wikibase-dump-filter#26]
Hey there :) 
So I'd like to get all cities and municipalities of the world. But for example some only have "municipality of [country]". The "municipality of [...]" item is a subclass of the "municipality" item. Would it be possible to only filter by the overall item and still get all entities that are instances of the different subclasses?

**Comment by maxlath** [comment]
there was a very similar case a few days ago: #24
wikibase-dump-filter is a "dumb" filter, that only works with the local data: you need to provide all the ids that you want to match as no graph resolution is done
