### ISSUE TITLE
Recommendation: Include pre-filtering as direct component of documentation

### ISSUE THREAD

**Issue by sabahzero** [maxlath/wikibase-dump-filter#35]
At the moment it's a brief line, but as it saves quite a bit of time for the user it may be good to have a paragraph or so directly in the [main documentation](https://github.com/maxlath/wikibase-dump-filter/blob/main/docs/cli.md) briefly describing what pre-filtering does why it's useful (that then also includes the hyperlink)

**Comment by maxlath** [comment]
I gave it a try in b381961, is that better?

**Comment by sabahzero** [comment]
Let me know if [this helps](https://github.com/maxlath/wikibase-dump-filter/compare/main...sabahzero:patch-1), adjusted slightly to hopefully reduce some repetition!

**Comment by sabahzero** [comment]
Hi @maxlath just wanted to check in if that was helpful

**Comment by maxlath** [comment]
@sabahzero I think I prefer my version :sweat_smile:

**Comment by sabahzero** [comment]
@maxlath no worries, I can understand!
