### ISSUE TITLE
Differing item numbers, issue with tool?

### ISSUE THREAD

**Issue by sabahzero** [maxlath/wikibase-dump-filter#40]
Hello!

I'm working from a MacOS v12.2, script is run on a server at our research institute (in the [Su Lab](github.com/suLab/). I've been using WDF and getting different results from @andrawaag ([https://github.com/andrawaag/wdsub](https://github.com/andrawaag/wdsub)) and @seyedahbr ([https://github.com/seyedahbr/wdumper](https://github.com/seyedahbr/wdumper)) and we're not entirely sure why this is the case.

We are using the same Wikidata dump (Jan 3 2022), takes between 5-7 hours to download. Here is [my script I then run using WDF with](https://github.com/sabahzero/WRP/blob/main/src/Jan3-2022/prefilter-script) and [sans prefilter](https://github.com/sabahzero/WRP/blob/main/src/Jan3-2022/prefilter-script_nogrep). 

The output is the same for both (with or sans prefilter), so we're wondering if it may be something with the tool or perhaps you can advise? 

One example: We expect to see ~1.2 million item pages for compounds. This is true for both Andra and Seyed using the same identifiers I have (P31:Q11173). However, I get ~18000 not 1.2 million

Thoughts on why this is the case?
Many thanks!

**Comment by maxlath** [comment]
The output being the same with or sans prefilter is rather a good news: going without prefilter should give the same results, only slower as there are more lines to parse.

As for the different results you get, I don't see why that would be the case. Could it be that you are not using the same WDF version? or maybe there was an error somewhere during the process that returned less results? A way to debug that could be to find the a/some results in the 1.2 million results output that are missing in the ~18000 output, put those missing results lines in a new `sample.ndjson` file, and then try to re-run the filter on it in your different setups: `cat sample.ndjson | wikibase-dump-filter --claim P31:Q11173`. Does it behave differently?

**Comment by sabahzero** [comment]
Hi @maxlath,
Thank you for the informative and reply. After chatting and troubleshooting with Andra and Seyed, I was able to sort out that it's an issue with the original dump I'm filtering from itself. So, good news in that your tool does work and output the 1.2 million example of compounds when I tried it from Andra's json file. I'll let you know if any issues arise going forward.
